server:
  port: 8090

#DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gee?useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#    schema:
#      classpath: db/schema.sql
#    data:
#      classpath: db/data.sql
    username: root
    password: root

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl